### PR TITLE
stream of events stopped working

### LINKED ISSUE #17: stream of events stopped working
## Describe the bug

With while lets streams stop working unnoticed when they receive e.g. None values.

## Expected behavior

Streams should recover easily.

## Additional context

while lets to loops :)

### PR DESCRIPTION
**Pull request by aserowy**
fixed #17

### CODE REVIEW

**Comment by aserowy** [comment]
@thomaszub first review 🍡

**Review by thomaszub — APPROVED** [review]
The change from while let to loops means two times a infinite loop.

**Comment by aserowy** [comment]
> The change from while let to loops means two times a infinite loop.

Yaeh, all of those loops are running in separate tasks. Thus, the only concerns are application drops. While the application drops, buffered events will eventually not get handled till the end. The trait off is simplicity in code :D

**Comment by aserowy** [comment]
i had no idea... :D

tokio streams are sending none if the stream fot closed. beyond options, results return closed events as well. thus, fixes for my anti-fixes incoming.

**Comment by aserowy** [comment]
#20

**Pull request merged**
